# Generated by Django 2.2.12 on 2020-05-05 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='song_thumb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist', models.CharField(max_length=100, null=True)),
                ('song_title', models.CharField(max_length=100, null=True)),
                ('album', models.CharField(max_length=100, null=True)),
                ('song_duration', models.FloatField(null=True)),
                ('img', models.ImageField(null=True, upload_to='pics')),
                ('song', models.FileField(null=True, upload_to='media')),
            ],
        ),
    ]
